import react from '@vitejs/plugin-react';
import path from 'path';
import { defineConfig } from 'vite';

function build(relativePath: string) {
  return path.resolve(__dirname, relativePath);
}

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '#lib': build('src/lib'),
      '#assets': build('src/assets'),
      '#components': build('src/components'),
      '#features/auth': build('src/features/auth'),
      '#features/auth/i18n': build('src/features/auth/i18n'),
      '#features/auth/domain': build('src/features/auth/domain'),
      '#features/auth/react': build('src/features/auth/react'),
      '#features/dashboard/react': build('src/features/dashboard/react'),
      '#features/home/react': build('src/features/home/react'),
      '#features/products': build('src/features/products'),
      '#features/products/i18n': build('src/features/products/i18n'),
      '#features/products/domain': build('src/features/products/domain'),
      '#features/products/infra': build('src/features/products/infra'),
      '#features/products/react': build('src/features/products/react'),
      '#features/projects': build('src/features/projects'),
      '#features/projects/i18n': build('src/features/projects/i18n'),
      '#features/projects/domain': build('src/features/projects/domain'),
      '#features/projects/infra': build('src/features/projects/infra'),
      '#features/projects/react': build('src/features/projects/react'),
      '#features/schools': build('src/features/schools'),
      '#features/schools/i18n': build('src/features/schools/i18n'),
      '#features/schools/domain': build('src/features/schools/domain'),
      '#features/schools/infra': build('src/features/schools/infra'),
      '#features/schools/react': build('src/features/schools/react'),
      '#features/settings/i18n': build('src/features/settings/i18n'),
      '#features/settings/domain': build('src/features/settings/domain'),
      '#features/settings/react': build('src/features/settings/react'),
      '#features/students': build('src/features/students'),
      '#features/students/i18n': build('src/features/students/i18n'),
      '#features/students/domain': build('src/features/students/domain'),
      '#features/students/infra': build('src/features/students/infra'),
      '#features/students/react': build('src/features/students/react'),
      '#features/klasses': build('src/features/klasses'),
      '#features/klasses/i18n': build('src/features/klasses/i18n'),
      '#features/klasses/domain': build('src/features/klasses/domain'),
      '#features/klasses/infra': build('src/features/klasses/infra'),
      '#features/klasses/react': build('src/features/klasses/react'),
      '#features/files': build('src/features/files'),
      '#features/files/i18n': build('src/features/files/i18n'),
      '#features/files/domain': build('src/features/files/domain'),
      '#features/files/infra': build('src/features/files/infra'),
      '#features/files/react': build('src/features/files/react'),
      '#layout': build('src/layout'),
      '#di/domain': build('src/lib/di/src/domain'),
      '#di/react': build('src/lib/di/src/react'),
      '#di': build('src/lib/di/src'),
      '#i18n/domain': build('src/features/_/i18n/src/domain'),
      '#i18n/react': build('src/features/_/i18n/src/react'),
      '#i18n': build('src/features/_/i18n/src'),
      '#routing/domain': build('src/features/_/routing/domain'),
      '#routing/react': build('src/features/_/routing/react'),
      '#routing': build('src/features/_/routing'),
      '#core/domain': build('src/features/_/core/domain'),
      '#core/react': build('src/features/_/core/react'),
      '#toast/domain': build('src/features/_/toast/domain'),
      '#toast/react': build('src/features/_/toast/react'),
      '#toast': build('src/features/_/toast'),
      '#mock': build('src/features/_/mock'),
    },
  },
});
